const errorCodes = {
  USER_ALREADY_EXISTS: 100,
  PLAYER_ALREADY_EXISTS: 101,
  ACHIEVEMENT_REGISTER_ALREADY_EXISTS: 102,
  BAD_REQUEST_ERROR: 103,
  USER_PASSWORD_DONT_MATCH: 200,
  TITLE_BELONGS_TO_PLAYER: 201,
  COULD_NOT_FIND_USER: 202,
  MISSING_PARAMETERS: 300,
  INVALID_TOKEN: 403,
  RESOURCE_NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
};

export default errorCodes;
